### ISSUE TITLE
wrong tag/branch chosen

### ISSUE THREAD

**Issue by tarfu** [azul3d/semver#12]
Hi,

i recognized that https://azul3d.org/semver.v1?go-get=1 points to the wrong tag.

it points to the tag v1 but there is a tag v1.0.1 which would be the one to choose.
I will try to commit a fix myself.

My version of semver is v2.

Regards,

Tobias

**Comment by slimsag** [comment]
Good news!

The tests I've just added also find that sorting of git refs _is actually reversed_! This means it would have always chosen the least greatest version in the same major version (e.g. `v1` over `v.1.2`).

**Comment by tarfu** [comment]
Had fixed this as well but forgot to push it, sry .

If you haven't fixed it til I get home I will push it as well.

Tobias
Am 21.01.2015 21:51 schrieb "Stephen Gutekanst" <notifications@github.com>:

**Comment by slimsag** [comment]
Everything should be good now. I've [released v2.0.1](http://azul3d.org/news/2015/semver-version-201.html) and it's up and running at `azul3d.org`.

`go get azul3d.org/semver.v1` now properly checks out `v1.0.1`

Cheers =)
