### ISSUE TITLE
Switch to "-unstable" instead of "-dev"

### ISSUE THREAD

**Issue by slimsag** [azul3d/semver#7]
We should switch to `vN-unstable` instead of `vN-dev`. Rational:

- The official [govers](https://github.com/rogpeppe/govers) tool now has support for `-unstable` in it.
- _unstable_ better implies that breaking changes may be made, as opposed to _dev_ which might imply otherwise.
- gopkg.in is now making use of _unstable_ instead of _dev_ now, clarity will be had by keeping a level of consistency.

**Comment by nathany** [comment]
:+1:

**Comment by slimsag** [comment]
I've [created a fork](https://github.com/slimsag/govers) of the govers tool that can be used to transition from `vN-dev` import paths to `vN-unstable` ones.
